---
- name: Add the ansible PPA.
  apt_repository:
    repo: "ppa:ansible/ansible"
    state: present

- name: Update the apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install software-properties-common.
  apt:
    name: software-properties-common
    state: present

- name: Install the git package.
  apt:
    name: git
    state: present

- name: Install the ansible package.
  apt:
    name: ansible
    state: present

- name: Update ansible configuration file.
  lineinfile:
    dest: /etc/ansible/ansible.cfg
    regexp: "^{{ item.key }} "
    insertafter: "#{{ item.key }} "
    line: "{{ item.key }} = {{ item.value }}"
  with_items:
    - { key: "force_color", value: "True" }
    - { key: "host_key_checking", value: "False" }
    - { key: "scp_if_ssh", value: "True" }
    - { key: "remote_tmp", value: "/tmp" }

- name: Install the python-boto package.
  apt:
    name: python-boto
    state: present

- name: Allow ssh login from the private OpenZFS instance
  authorized_key:
    user: "{{ ansible_ssh_user }}"
    key: "{{ item }}"
  with_file:
    - openzfs-jenkins-private.id_rsa.pub

- name: Install FTP package
  apt:
    name: vsftpd
    state: present

- name: Enable anonymous FTP downloads
  lineinfile:
    dest: /etc/vsftpd.conf
    regexp: "^{{ item.key }}="
    insertafter: "#{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - { key: "anonymous_enable", value: "YES" }
  notify: restart vsftpd
